name: Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:    

  check-installer:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
      
    - name: Restore dependencies
      run: dotnet restore source/gpm.Installer/gpm.Installer.csproj
    - name: Build
      run: dotnet build source/gpm.Installer/gpm.Installer.csproj --no-restore

  check-wpf:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
      
    - name: Publish
      run: dotnet publish source/gpm.Installer.WPF/gpm.Installer.WPF.csproj -o publish-win
    - run: Compress-Archive -Path publish-win\* -DestinationPath gpm-Installer-wpf.zip
    

      

   
