name: PublishNuget

on: 
  workflow_dispatch:

jobs:
  build:
    name: release-wpf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore source/gpm.Installer/gpm.Installer.csproj
    - name: Build
      run: dotnet build source/gpm.Installer/gpm.Installer.csproj --no-restore
      
    - name: publish nuget
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: source/gpm.Installer/gpm.Installer.csproj
        NUGET_KEY: ${{secrets.NUGET_KEY}}
