name: PublishNuget

on: 
  workflow_dispatch:

jobs:
  build:
    name: release-wpf
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Restore dependencies
      run: dotnet restore source/gpm.Installer/gpm.Installer.csproj

    - name: Build
      run: dotnet build source/gpm.Installer/gpm.Installer.csproj --no-restore

    - name: publish core package to NuGet
      run: dotnet nuget push source/gpm/source/gpm.Core/nupkg/*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
    - name: publish installer package to NuGet
      run: dotnet nuget push source/gpm.Installer/nupkg/*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
