name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    name: release-wpf
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
      
    - name: Publish
      run: dotnet publish source/gpm.Installer.WPF/gpm.Installer.WPF.csproj -o publish-win
    - run: Compress-Archive -Path publish-win\* -DestinationPath gpm-Installer-wpf.zip

    - uses: ncipollo/release-action@v1
      with:
        draft: true
        generateReleaseNotes: true
        artifacts: "*.zip"
#        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}

